apiVersion: v2
appVersion: v8.0.1
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.6.0
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: https://charts.bitnami.com/bitnami
  version: 19.5.8
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.0.0
description: A Helm chart that Deploys RapidPro and its dependency
icon: https://raw.githubusercontent.com/rapidpro/rapidpro/gh-pages/images/rapidpro.ico
maintainers:
- email: techops@ona.io
  name: Ona Engineering
name: rapidpro
type: application
version: 1.0.1
